### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by watamario15** [littlegirl0820/semi-b#11]
@littlegirl0820 @Ryu-Okamoto @tth-test @Tamaki046
この制作物についてライセンスを設定するのを忘れていたので、ここで決定しようと思います。

## なぜ必要？
今回は、それなりに役に立ちそうなものを作成する運びとなりました。チームはゼミ B の終講とともに解散する訳ですが、今後も自主的に改良して公開したいメンバーがいるかもしれません。また、ここでの実装を後で参考にしたいこともあるかもしれません。あるいは、Public にしているので外部の人が参考にすることもあるかもしれません。しかし、ライセンスが不明瞭だと、これらのことを (法的に) 安全に行うために毎回開発メンバー全員から同意を得る必要が生じます。なので、**その同意を今 1 発で済ませておこう**というのがライセンス設定の 1 つの重要な意義です。

## 案
自分としては、このプロジェクトの最も重要な部分は大喜利と伝言ゲームを融合させた「アイデア」の部分にあり、その実装であるこのリポジトリ本体は著作権を主張するレベルのものではないと見ています (知っての通り、アイデアは著作権保護の対象とならない)。よって、**著作権を完全に放棄する、それが法的に不可能な場合はパブリックドメイン相当の権利を利用者に許可する [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.ja)** が妥当だと考えています。ライセンスを付けずに公開していた時点で、多くの人は元々そのつもりだったのではないかとも思っています。この方針に同意する場合は、返信で意思表示をお願いします (明示的なものとしたいので、リアクションはカウントしない)。

もちろん、これはチームメンバー全員が意思を持ち得るものなので、他の案も返信という形で受け付けます。個人的には MIT License のような緩めのライセンスであれば許容範囲かなと考えています。

**Comment by Ryu-Okamoto** [comment]
CC0,同意🤞

**Comment by Tamaki046** [comment]
ライセンスについて、放あるいはパブリックドメイン相当のものを付与することに同意します。

ゲ`ムk案者としても、あくまで授Iの一hであり商婴胜螭扦悉胜い郡帷长违博`ムでひとΔ堡筏瑜Δ胜螭扑激盲皮い胜い扦埂￥饯欷瑜辘狻袱长违博`ムを多くの人にSしんでもらいたい」「Xい莩证沥钎播楗播樾Δ盲七[んでもらいたい」という莩证沥畏饯R倒的にいです。

gHのプログラム_kは他メンバ`にほぼ任せっきりだった身なのでコ`ドにvしてくは言えないかもしれませんが、「葺Xに[んでほしい」というのがゲ`ムk案者としての1番のいです。

Outlook for Android<https://aka.ms/AAb9ysg>を取得
________________________________
From: watamario15 ***@***.***>
Sent: Tuesday, February 14, 2023 11:57:44 PM
To: littlegirl0820/semi-b ***@***.***>
Cc: TAMAKI Fumito ***@***.***>; Assign ***@***.***>
Subject: [littlegirl0820/semi-b] ライセンス (Issue #11)


@littlegirl0820<https://github.com/littlegirl0820> @Ryu-Okamoto<https://github.com/Ryu-Okamoto> @tth-test<https://github.com/tth-test> @Tamaki046<https://github.com/Tamaki046>
この制作物についてライセンスをO定するのを忘れていたので、ここでQ定しようと思います。

なぜ必要？

今回は、それなりに役に立ちそうなものを作成する\びとなりました。チ`ムはゼミ B のKvとともに解散するUですが、今後も自主的に改良して公_したいメンバ`がいるかもしれません。また、ここでのg装を後で参考にしたいこともあるかもしれません。あるいは、Public にしているので外部の人が参考にすることもあるかもしれません。しかし、ライセンスが不明tだと、これらのことを (法的に) 安全に行うために盎亻_kメンバ`全Tから同意を得る必要が生じます。なので、その同意を今 1 kでgませておこうというのがライセンスO定の 1 つの重要な意xです。

案

自分としては、このプロジェクトの最も重要な部分は大喜利と谎豫博`ムを融合させた「アイデア」の部分にあり、そのg装であるこのリポジトリ本体は著作丐蛑するレベルのものではないとています (知っての通り、アイデアは著作乇Ｗoの象とならない)。よって、著作丐蛲耆朔する、それが法的に不可能な龊悉膝靴芝辚氓丧幞ぅ笙嗟堡乩蚶谜撙嗽S可する CC0<https://creativecommons.org/publicdomain/zero/1.0/deed.ja> が妥当だと考えています。ライセンスを付けずに公_していたr点で、多くの人は元々そのつもりだったのではないかとも思っています。この方に同意する龊悉稀⒎敌扭且馑急硎兢颏いします (明示的なものとしたいので、リアクションはカウントしない)。

もちろん、これはチ`ムメンバ`全Tが意思を持ち得るものなので、他の案も返信という形で受け付けます。人的には MIT License のようなめのライセンスであればS容�欷胜瓤激à皮い蓼埂

―

**Comment by watamario15** [comment]
@Tamaki046 
文字化けが半端ないので、直接 GitHub 上で回答してもらえると。同意は読み取れましたが、補足情報がかなりアレな状態になっています。

**Comment by Tamaki046** [comment]
メールで確認・返信したので文字化けしてしまいました。すみません。本文をもう一度送っておきます。

ライセンスについて、放棄あるいはパブリックドメイン相当のものを付与することに同意します。

ゲーム発案者としても、あくまで授業の一環であり商売なんかではないため、このゲームでひと儲けしようなんて思っていないです。それよりも「このゲームを多くの人に楽しんでもらいたい」「軽い気持ちでゲラゲラ笑って遊んでもらいたい」という気持ちの方が圧倒的に強いです。

実際のプログラム開発は他メンバーにほぼ任せっきりだった身なのでコードに関して強くは言えないかもしれませんが、「気軽に遊んでほしい」というのがゲーム発案者としての1番の願いです。

**Comment by watamario15** [comment]
ちなみに、CC0 は文字通り何の制限も課さないので、商用利用も禁止しません。なので、儲けることも許容されます。ただし、この権利は開発メンバーと無関係な人にも与えられることになります。まあ、仮に外部者によるソースコードの利用を禁止したところでクローンを 1 から実装するのは大して難しくないので、これが問題になることはないだろうという感じです。

**Comment by littlegirl0820** [comment]
CC0同意です。

**Comment by watamario15** [comment]
@tth-test 気付いてる～？

**Comment by tth-test** [comment]
反応遅れてしまい、すみません。CC0に同意します。
